//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int Id { get; set; }
        public string stu_name { get; set; }
        public string stu_batch { get; set; }
        public string stu_stream { get; set; }
        public string stu_email { get; set; }
        public string stu_mno { get; set; }
    }
}
